<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DailyReportSeeder extends Seeder
{
    public function run(): void
    {
        $reports = [
            [
                'user_id' => 2,
                'siswa_id' => 1,
                'tanggal' => '2024-04-25',
                'mood' => 'Senang',
                'activity' => 'Bermain puzzle, menggambar, dan bernyanyi bersama teman-teman',
                'sarapan_pagi' => 'Nasi goreng dan susu',
                'sarapan_status' => 5,
                'makan_siang' => 'Nasi, ayam goreng, sayur bayam',
                'makan_siang_status' => 5,
                'snack_sore' => 'Biskuit dan jus jeruk',
                'snack_status' => 4,
                'minum_air_putih' => '500',
                'minum_susu' => '200',
                'tidur_siang' => true,
                'tidur_siang_durasi' => '1.5 jam',
                'bak' => true,
                'bak_frekuensi' => 3,
                'bab' => true,
                'bab_frekuensi' => 1,
                'kebutuhan_besok' => 'Bawa baju ganti',
                'catatan_khusus' => 'Aisyah sangat aktif hari ini dan senang bermain dengan teman-temannya',
                'catatan_insiden' => null,
                'foto_kegiatan' => null,
                'is_final' => true,
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
            [
                'user_id' => 4,
                'siswa_id' => 2,
                'tanggal' => '2024-04-25',
                'mood' => 'Antusias',
                'activity' => 'Belajar mengenal huruf, bermain balok, dan olahraga ringan',
                'sarapan_pagi' => 'Roti dan susu coklat',
                'sarapan_status' => 4,
                'makan_siang' => 'Nasi, ikan goreng, tahu tempe',
                'makan_siang_status' => 5,
                'snack_sore' => 'Buah potong',
                'snack_status' => 5,
                'minum_air_putih' => '600',
                'minum_susu' => '250',
                'tidur_siang' => true,
                'tidur_siang_durasi' => '2 jam',
                'bak' => true,
                'bak_frekuensi' => 4,
                'bab' => true,
                'bab_frekuensi' => 1,
                'kebutuhan_besok' => null,
                'catatan_khusus' => 'Budi sangat antusias belajar huruf hari ini',
                'catatan_insiden' => null,
                'foto_kegiatan' => null,
                'is_final' => true,
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
            [
                'user_id' => 2,
                'siswa_id' => 3,
                'tanggal' => '2024-04-25',
                'mood' => 'Senang',
                'activity' => 'Menggambar, bermain pasir, dan mendengarkan cerita',
                'sarapan_pagi' => 'Bubur ayam',
                'sarapan_status' => 5,
                'makan_siang' => 'Nasi, rendang, sayur',
                'makan_siang_status' => 4,
                'snack_sore' => 'Kue dan teh manis',
                'snack_status' => 5,
                'minum_air_putih' => '450',
                'minum_susu' => '200',
                'tidur_siang' => true,
                'tidur_siang_durasi' => '1 jam',
                'bak' => true,
                'bak_frekuensi' => 3,
                'bab' => true,
                'bab_frekuensi' => 1,
                'kebutuhan_besok' => null,
                'catatan_khusus' => 'Zahra sangat kreatif dalam menggambar',
                'catatan_insiden' => null,
                'foto_kegiatan' => null,
                'is_final' => true,
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
            [
                'user_id' => 2,
                'siswa_id' => 1,
                'tanggal' => '2024-04-26',
                'mood' => 'Senang',
                'activity' => 'Bermain musik, menari, dan belajar angka',
                'sarapan_pagi' => 'Nasi uduk dan telur',
                'sarapan_status' => 5,
                'makan_siang' => 'Nasi, ayam bakar, sayur asem',
                'makan_siang_status' => 5,
                'snack_sore' => 'Donat dan susu',
                'snack_status' => 4,
                'minum_air_putih' => '550',
                'minum_susu' => '200',
                'tidur_siang' => true,
                'tidur_siang_durasi' => '1.5 jam',
                'bak' => true,
                'bak_frekuensi' => 3,
                'bab' => false,
                'bab_frekuensi' => 0,
                'kebutuhan_besok' => null,
                'catatan_khusus' => 'Aisyah mulai bisa menghitung 1-10',
                'catatan_insiden' => null,
                'foto_kegiatan' => null,
                'is_final' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($reports as $report) {
            DB::table('daily_reports')->insert($report);
        }
    }
}
