<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PembayaranSppSeeder extends Seeder
{
        public function run(): void
    {
        DB::table('pembayaran_spp')->insert([
            [
                'siswa_id' => 1,
                'kelas_id' => 2,
                'bulan' => 'Januari',
                'tahun' => 2024,
                'biaya' => 1800000.00,
                'tanggal_bayar' => '2024-01-05',
                'metode_bayar' => 'transfer',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonths(3),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'siswa_id' => 1,
                'kelas_id' => 2,
                'bulan' => 'Februari',
                'tahun' => 2024,
                'biaya' => 1800000.00,
                'tanggal_bayar' => '2024-02-03',
                'metode_bayar' => 'transfer',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'siswa_id' => 1,
                'kelas_id' => 2,
                'bulan' => 'Maret',
                'tahun' => 2024,
                'biaya' => 1800000.00,
                'tanggal_bayar' => '2024-03-04',
                'metode_bayar' => 'transfer',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'siswa_id' => 1,
                'kelas_id' => 2,
                'bulan' => 'April',
                'tahun' => 2024,
                'biaya' => 1800000.00,
                'tanggal_bayar' => null,
                'metode_bayar' => null,
                'bukti_bayar' => null,
                'status_bayar' => 'pending',
                'catatan_admin' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 2,
                'kelas_id' => 3,
                'bulan' => 'Januari',
                'tahun' => 2024,
                'biaya' => 2000000.00,
                'tanggal_bayar' => '2024-01-10',
                'metode_bayar' => 'cash',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonths(3),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'siswa_id' => 2,
                'kelas_id' => 3,
                'bulan' => 'Februari',
                'tahun' => 2024,
                'biaya' => 2000000.00,
                'tanggal_bayar' => '2024-02-08',
                'metode_bayar' => 'cash',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'siswa_id' => 2,
                'kelas_id' => 3,
                'bulan' => 'Maret',
                'tahun' => 2024,
                'biaya' => 2000000.00,
                'tanggal_bayar' => '2024-03-07',
                'metode_bayar' => 'cash',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'siswa_id' => 2,
                'kelas_id' => 3,
                'bulan' => 'April',
                'tahun' => 2024,
                'biaya' => 2000000.00,
                'tanggal_bayar' => '2024-04-05',
                'metode_bayar' => 'cash',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subDays(21),
                'updated_at' => now()->subDays(21),
            ],
            [
                'siswa_id' => 3,
                'kelas_id' => 2,
                'bulan' => 'Maret',
                'tahun' => 2024,
                'biaya' => 1800000.00,
                'tanggal_bayar' => '2024-03-22',
                'metode_bayar' => 'transfer',
                'bukti_bayar' => null,
                'status_bayar' => 'diterima',
                'catatan_admin' => null,
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'siswa_id' => 3,
                'kelas_id' => 2,
                'bulan' => 'April',
                'tahun' => 2024,
                'biaya' => 1800000.00,
                'tanggal_bayar' => null,
                'metode_bayar' => null,
                'bukti_bayar' => null,
                'status_bayar' => 'pending',
                'catatan_admin' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }  }
