<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('siswa')->insert([
            [
                'user_id' => 5,
                'kelas_id' => 2,
                'guru_id' => 1,
                'nama_lengkap' => 'Aisyah Putri Dahlan',
                'nama_panggilan' => 'Aisyah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '2021-05-15',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'anak_ke' => 1,
                'jumlah_saudara_kandung' => 0,
                'bahasa_sehari_hari' => 'Indonesia',
                'foto_siswa' => null,
                'berat_badan' => 12.5,
                'tinggi_badan' => 85.0,
                'golongan_darah' => 'A',
                'riwayat_penyakit' => null,
                'alasan_rawat_inap' => null,
                'riwayat_alergi_makanan' => null,
                'ayah_nama_lengkap' => 'Ahmad Dahlan',
                'ayah_tempat_lahir' => 'Padang',
                'ayah_tanggal_lahir' => '1990-03-10',
                'ayah_pekerjaan' => 'Wiraswasta',
                'ayah_pendidikan_terakhir' => 'S1',
                'ayah_nomor_identitas' => '1371031003900001',
                'ayah_alamat_rumah' => 'Jl. Pemuda No. 123, Padang',
                'ayah_telepon_rumah' => '0751123456',
                'ayah_alamat_kantor' => 'Jl. Hayam Wuruk No. 45, Padang',
                'ayah_telepon_kantor' => '0751234567',
                'ayah_no_hp' => '6281234567894',
                'ibu_nama_lengkap' => 'Siti Aminah',
                'ibu_tempat_lahir' => 'Bukittinggi',
                'ibu_tanggal_lahir' => '1992-07-20',
                'ibu_pekerjaan' => 'Ibu Rumah Tangga',
                'ibu_pendidikan_terakhir' => 'S1',
                'ibu_nomor_identitas' => '1371072007920002',
                'ibu_alamat_rumah' => 'Jl. Pemuda No. 123, Padang',
                'ibu_telepon_rumah' => '0751123456',
                'ibu_alamat_kantor' => null,
                'ibu_telepon_kantor' => null,
                'ibu_no_hp' => '6281234567897',
                'kontak_darurat_nama_lengkap' => 'Fatimah Zahra',
                'kontak_darurat_hubungan' => 'Nenek',
                'kontak_darurat_pekerjaan' => 'Pensiunan',
                'kontak_darurat_nomor_identitas' => '1371010101650001',
                'kontak_darurat_alamat_rumah' => 'Jl. Veteran No. 67, Padang',
                'kontak_darurat_telepon_rumah' => '0751345678',
                'kontak_darurat_alamat_kantor' => null,
                'kontak_darurat_telepon_kantor' => null,
                'kontak_darurat_no_hp' => '6281234567898',
                'lokasi_pendaftaran' => 'Ulak Karang',
                'tanggal_pendaftaran' => '2024-01-10',
                'status_siswa' => true,
                'jenis_pembayaran' => 'transfer',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'kelas_id' => 3,
                'guru_id' => 3,
                'nama_lengkap' => 'Budi Santoso Junior',
                'nama_panggilan' => 'Budi',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '2020-08-22',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'anak_ke' => 1,
                'jumlah_saudara_kandung' => 1,
                'bahasa_sehari_hari' => 'Indonesia',
                'foto_siswa' => null,
                'berat_badan' => 15.0,
                'tinggi_badan' => 95.0,
                'golongan_darah' => 'B',
                'riwayat_penyakit' => null,
                'alasan_rawat_inap' => null,
                'riwayat_alergi_makanan' => 'Kacang',
                'ayah_nama_lengkap' => 'Budi Santoso',
                'ayah_tempat_lahir' => 'Jakarta',
                'ayah_tanggal_lahir' => '1988-11-05',
                'ayah_pekerjaan' => 'PNS',
                'ayah_pendidikan_terakhir' => 'S2',
                'ayah_nomor_identitas' => '1371110511880001',
                'ayah_alamat_rumah' => 'Jl. Diponegoro No. 89, Padang',
                'ayah_telepon_rumah' => '0751456789',
                'ayah_alamat_kantor' => 'Jl. Sudirman No. 12, Padang',
                'ayah_telepon_kantor' => '0751567890',
                'ayah_no_hp' => '6281234567895',
                'ibu_nama_lengkap' => 'Rina Kusuma',
                'ibu_tempat_lahir' => 'Padang',
                'ibu_tanggal_lahir' => '1990-04-12',
                'ibu_pekerjaan' => 'Guru',
                'ibu_pendidikan_terakhir' => 'S1',
                'ibu_nomor_identitas' => '1371041204900002',
                'ibu_alamat_rumah' => 'Jl. Diponegoro No. 89, Padang',
                'ibu_telepon_rumah' => '0751456789',
                'ibu_alamat_kantor' => 'Jl. Veteran No. 34, Padang',
                'ibu_telepon_kantor' => '0751678901',
                'ibu_no_hp' => '6281234567899',
                'kontak_darurat_nama_lengkap' => 'Siti Rahmah',
                'kontak_darurat_hubungan' => 'Bibi',
                'kontak_darurat_pekerjaan' => 'Dokter',
                'kontak_darurat_nomor_identitas' => '1371020202750001',
                'kontak_darurat_alamat_rumah' => 'Jl. Ahmad Yani No. 23, Padang',
                'kontak_darurat_telepon_rumah' => '0751789012',
                'kontak_darurat_alamat_kantor' => 'RS Siti Rahmah, Padang',
                'kontak_darurat_telepon_kantor' => '0751890123',
                'kontak_darurat_no_hp' => '6281234567900',
                'lokasi_pendaftaran' => 'Marapalam',
                'tanggal_pendaftaran' => '2024-02-15',
                'status_siswa' => true,
                'jenis_pembayaran' => 'cash',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'kelas_id' => 2,
                'guru_id' => 1,
                'nama_lengkap' => 'Zahra Amelia',
                'nama_panggilan' => 'Zahra',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '2021-12-03',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'anak_ke' => 2,
                'jumlah_saudara_kandung' => 1,
                'bahasa_sehari_hari' => 'Indonesia',
                'foto_siswa' => null,
                'berat_badan' => 11.8,
                'tinggi_badan' => 82.0,
                'golongan_darah' => 'O',
                'riwayat_penyakit' => null,
                'alasan_rawat_inap' => null,
                'riwayat_alergi_makanan' => null,
                'ayah_nama_lengkap' => 'Rizki Pratama',
                'ayah_tempat_lahir' => 'Padang',
                'ayah_tanggal_lahir' => '1989-06-18',
                'ayah_pekerjaan' => 'Pengusaha',
                'ayah_pendidikan_terakhir' => 'S1',
                'ayah_nomor_identitas' => '1371061806890001',
                'ayah_alamat_rumah' => 'Jl. Khatib Sulaiman No. 156, Padang',
                'ayah_telepon_rumah' => '0751234890',
                'ayah_alamat_kantor' => 'Jl. Bypass No. 78, Padang',
                'ayah_telepon_kantor' => '0751345901',
                'ayah_no_hp' => '6281234567896',
                'ibu_nama_lengkap' => 'Citra Dewi',
                'ibu_tempat_lahir' => 'Payakumbuh',
                'ibu_tanggal_lahir' => '1991-09-25',
                'ibu_pekerjaan' => 'Desainer',
                'ibu_pendidikan_terakhir' => 'S1',
                'ibu_nomor_identitas' => '1371092509910002',
                'ibu_alamat_rumah' => 'Jl. Khatib Sulaiman No. 156, Padang',
                'ibu_telepon_rumah' => '0751234890',
                'ibu_alamat_kantor' => 'Jl. Pemuda No. 90, Padang',
                'ibu_telepon_kantor' => '0751456012',
                'ibu_no_hp' => '6281234567896',
                'kontak_darurat_nama_lengkap' => 'Dewi Sartika',
                'kontak_darurat_hubungan' => 'Kakak',
                'kontak_darurat_pekerjaan' => 'Guru',
                'kontak_darurat_nomor_identitas' => '1371030303880001',
                'kontak_darurat_alamat_rumah' => 'Jl. Hayam Wuruk No. 45, Padang',
                'kontak_darurat_telepon_rumah' => '0751567123',
                'kontak_darurat_alamat_kantor' => 'SD Negeri 01, Padang',
                'kontak_darurat_telepon_kantor' => '0751678234',
                'kontak_darurat_no_hp' => '6281234567901',
                'lokasi_pendaftaran' => 'Ulak Karang',
                'tanggal_pendaftaran' => '2024-03-20',
                'status_siswa' => true,
                'jenis_pembayaran' => 'transfer',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
